import turtle
monty = turtle.Turtle()
monty.shape("turtle")

#wierza z lewej
monty.color('blue')
monty.fillcolor('blue')
monty.begin_fill()
monty.left(90)
monty.forward(30)
monty.left(30)
monty.forward(7)
monty.right(30)
monty.forward(7)
monty.right(90)
monty.forward(5)
monty.right(90)
monty.forward(5)
monty.left(90)
monty.forward(5)
monty.left(90)
monty.forward(5)
monty.right(90)
monty.forward(5)
monty.right(90)
monty.forward(5)
monty.left(90)
monty.forward(5)
monty.left(90)
monty.forward(5)
monty.right(90)
monty.forward(5)
monty.right(90)
monty.forward(7)
monty.right(30)
monty.forward(7)
monty.left(30)
monty.forward(10)

#srodek
monty.left(90)
monty.forward(50)
monty.left(90)
monty.forward(10)

#lewa wierza
monty.left(30)
monty.forward(7)
monty.right(30)
monty.forward(7)
monty.right(90)
monty.forward(5)
monty.right(90)
monty.forward(5)
monty.left(90)
monty.forward(5)
monty.left(90)
monty.forward(5)
monty.right(90)
monty.forward(5)
monty.right(90)
monty.forward(5)
monty.left(90)
monty.forward(5)
monty.left(90)
monty.forward(5)
monty.right(90)
monty.forward(5)
monty.right(90)
monty.forward(7)
monty.right(30)
monty.forward(7)
monty.left(30)
monty.forward(35)
monty.right(90)
monty.forward(86)
monty.end_fill()


monty.color('white')
monty.fillcolor('white')
monty.right(180)
monty.penup()
monty.forward(40)

monty.pendown()
monty.begin_fill()
monty.forward(6)
monty.left(90)
monty.forward(10)
monty.left(90)
monty.forward(6)
monty.left(90)
monty.forward(10)
monty.left(90)

monty.goto(43,3)
monty.circle(3)
monty.end_fill()

monty.penup()


monty.goto(3,25)

monty.down()

monty.color('white')
monty.fillcolor('white')
monty.begin_fill()
monty.forward(4)
monty.left(90)
monty.forward(6)
monty.left(90)
monty.forward(4)
monty.left(90)
monty.forward(6)
monty.end_fill()

monty.penup()
monty.goto(10,25)
monty.down()

monty.color('white')
monty.fillcolor('white')
monty.begin_fill()
monty.left(90)
monty.forward(4)
monty.left(90)
monty.forward(6)
monty.left(90)
monty.forward(4)
monty.left(90)
monty.forward(6)
monty.end_fill()

monty.penup()
monty.goto(80,25)
monty.down()

monty.color('white')
monty.fillcolor('white')
monty.begin_fill()
monty.left(90)
monty.forward(4)
monty.left(90)
monty.forward(6)
monty.left(90)
monty.forward(4)
monty.left(90)
monty.forward(6)
monty.end_fill()


monty.penup()
monty.goto(76,25)
monty.down()

monty.color('white')
monty.fillcolor('white')
monty.begin_fill()
monty.right(90)
monty.forward(4)
monty.right(90)
monty.forward(6)
monty.right(90)
monty.forward(4)
monty.right(90)
monty.forward(6)
monty.end_fill()


monty.penup()
monty.goto(33,20)
monty.down()

monty.color('black')
monty.fillcolor('black')
monty.begin_fill()

monty.left(180)
monty.forward(30)

monty.right(90)
monty.forward(4)
monty.right(90)
monty.forward(4)
monty.left(90)
monty.forward(4)
monty.left(90)
monty.forward(4)
monty.right(90)
monty.forward(4)
monty.right(90)
monty.forward(4)
monty.left(90)
monty.forward(4)
monty.left(90)
monty.forward(4)
monty.right(90)
monty.forward(4)


monty.right(90)
monty.forward(30)
monty.end_fill()